-- Intentionally written a little quirky to provoke code generator

CREATE USER DOCKER
    IDENTIFIED BY password
    QUOTA 50M ON SYSTEM;

GRANT create session TO DOCKER;
GRANT create table TO DOCKER;
GRANT create view TO DOCKER;
GRANT create any trigger TO DOCKER;
GRANT create any procedure TO DOCKER;
GRANT create sequence TO DOCKER;
GRANT create synonym TO DOCKER;



CREATE SEQUENCE DOCKER.ONE_COL_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DOCKER.ONE_COLUMN_GENERATED_ID_ORACLE (
    id NUMBER(9) NOT NULL,
    CONSTRAINT ONE_COL_ORACLE_PK PRIMARY KEY (id)
);


CREATE OR REPLACE TRIGGER DOCKER.one_col_trg 
BEFORE INSERT ON DOCKER.ONE_COLUMN_GENERATED_ID_ORACLE 
FOR EACH ROW
WHEN (new.id IS NULL)
BEGIN
    :new.id := DOCKER.ONE_COL_SEQ.NEXTVAL;
END;
/


CREATE TABLE DOCKER.ONE_COLUMN_NATURAL_ID_ORACLE (
    id VARCHAR(9) NOT NULL,
    CONSTRAINT ONE_COL_NAT_ORACLE_PK PRIMARY KEY (id)
);


CREATE TABLE DOCKER.DATA_TYPES_ORACLE (
	ID VARCHAR2(100) not null,
	"VARCHAR" VARCHAR(100) not null,
	"VARCHAR2" VARCHAR2(100) not null,
	CHAR10 CHAR(10) not null,
	CHAR1 CHAR(1) not null,
	"BINARY_DOUBLE" BINARY_DOUBLE not null,
	"BINARY_FLOAT" BINARY_FLOAT not null,
	"BLOB" BLOB not null,
	"CLOB" CLOB not null,
	"NLOB" NCLOB not null,
	"DATE" DATE not null,
	"TIMESTAMP" TIMESTAMP not null,
	"TIMESTAMP_TZ" TIMESTAMP WITH TIME ZONE not null,
	NUMBER_TEN_TWO NUMBER(10, 2) not null,
	NUMBER_NINE_ZERO NUMBER(9, 0) not null, -- Fits in int
	NUMBER_TEN_ZERO NUMBER(10, 0) not null, -- Does not fit in int but fits in long
	NUMBER_EIGHTEEN_ZERO NUMBER(18, 0) not null, -- Fits in long
	NUMBER_NINETEEN_ZERO NUMBER(19, 0) not null, -- Does not fit in long
	CONSTRAINT DATA_TYPES_ORACLE_PK PRIMARY KEY (ID)
);

CREATE TABLE DOCKER.COLOR_ENUM_ORACLE (
    name VARCHAR(9) NOT NULL,
    CONSTRAINT COLOR_ENUM_ORACLE_PK PRIMARY KEY (name)
);

INSERT INTO DOCKER.COLOR_ENUM_ORACLE (name) VALUES ('RED');
INSERT INTO DOCKER.COLOR_ENUM_ORACLE (name) VALUES ('GREEN');
INSERT INTO DOCKER.COLOR_ENUM_ORACLE (name) VALUES ('BLUE');

CREATE SEQUENCE DOCKER.BAZ_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DOCKER.BAZ_ORACLE (
    id NUMBER(9) NOT NULL,
    name VARCHAR(30) NOT NULL,
    color VARCHAR(9),
	created_at TIMESTAMP NOT NULL,
	changed_at TIMESTAMP,
	created_by VARCHAR(50) NOT NULL,
	changed_by VARCHAR(50),
    version NUMBER(9, 0),
    CONSTRAINT BAZ_ORACLE_PK PRIMARY KEY (id),
    CONSTRAINT COLOR_FK FOREIGN KEY (color) REFERENCES DOCKER.COLOR_ENUM_ORACLE (name)
);


-- No identity functionality in Oracle 11c. And no 
-- Express edition of Oracle 12c on Docker hub. 
-- Hence this trigger.
CREATE OR REPLACE TRIGGER DOCKER.baz_trg 
BEFORE INSERT ON DOCKER.BAZ_ORACLE 
FOR EACH ROW
WHEN (new.id IS NULL)
BEGIN
    :new.id := DOCKER.BAZ_SEQ.NEXTVAL;
END;
/


CREATE VIEW DOCKER.BAZ_VIEW_ORACLE(ID, NAME, COLOR) AS
SELECT id, name, color FROM DOCKER.BAZ_ORACLE;
