

CREATE TABLE IF NOT EXISTS ONE_COLUMN_NATURAL_ID_MYSQL (
id VARCHAR(10) NOT NULL,
PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS COLOR_ENUM_MYSQL (
id IDENTITY NOT NULL,
name VARCHAR(30) NOT NULL,
PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS BazMysql (
id IDENTITY NOT NULL,
changed_at TIMESTAMP NOT NULL,
changed_by VARCHAR(50) NOT NULL,
color_enum_mysql_id INTEGER,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(50) NOT NULL,
name VARCHAR(30) NOT NULL,
version INTEGER,
PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS ONE_COLUMN_GENERATED_ID_MYSQL (
id IDENTITY NOT NULL,
PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS DATA_TYPES_MYSQL (
id IDENTITY NOT NULL,
bigint BIGINT,
bit BOOLEAN,
blob BLOB,
bool BOOLEAN,
date DATE,
datetime TIMESTAMP,
decimal_eighteen_zero BIGINT,
decimal_nine_zero INTEGER,
decimal_nineteen_zero DECIMAL(19, 0),
decimal_ten_two DECIMAL(10, 2),
decimal_ten_zero BIGINT,
double DOUBLE,
float REAL,
int INTEGER,
integer INTEGER,
json VARCHAR(0),
mediumint INTEGER,
smallint INTEGER,
text VARCHAR(65535),
time TIME,
timestamp TIMESTAMP,
tinyblob BINARY255,
tinyint INTEGER,
varchar_10 VARCHAR(10),
varchar_binary_10 BINARY10,
year INTEGER,
PRIMARY KEY(id));

ALTER TABLE BazMysql
ADD FOREIGN KEY (color_enum_mysql_id)
REFERENCES COLOR_ENUM_MYSQL(id);

MERGE INTO COLOR_ENUM_MYSQL(id, name) VALUES(1, 'RED');
MERGE INTO COLOR_ENUM_MYSQL(id, name) VALUES(2, 'GREEN');
MERGE INTO COLOR_ENUM_MYSQL(id, name) VALUES(3, 'BLUE');
